---
# defaults file for tm_silent_setup
db:
  db_user: dsm
  db_name: ansible
  db_password: ansible

pre_package:
  - bash
  - openssl
  - python-devel
  - gcc
  - python-pip
  - postgresql-devel

pip_package:
  - psycopg2

dir_permission:
  - /usr/lib64/python2.7/site-packages/psycopg2
  - /usr/lib64/python2.7/site-packages/psycopg2-2.8.6-py2.7.egg-info

uninstall_postgres:
  - python-devel
  - postgresql
  - postgresql-server

remove_dir:
  - /var/lib/pgsql