---
vmware_ci_vcsa_services_disabled:
  6.7.0:
    - vmcam
    - vmware-imagebuilder
    - vmware-mbcs
    - vmware-netdumper
    - vmware-rbd-watchdog
    - vmware-vcha
    - vsan-dps
    - vsphere-client
    - vsphere-ui
  7.0.0:
    - vmcam
    - vmware-imagebuilder
    - vmware-netdumper
    - vmware-rbd-watchdog
    - vmware-vcha
  7.0.1:
    - vmcam
    - vmware-imagebuilder
    - vmware-netdumper
    - vmware-rbd-watchdog
    - vmware-vcha
vmware_ci_vcsa_services_enabled:
  6.7.0:
    - applmgmt
    - lwsmd
    - pschealth
    - vmafdd
    - vmcad
    - vmdird
    - vmdnsd
    - vmonapi
    - vmware-analytics
    - vmware-cis-license
    - vmware-cm
    - vmware-content-library
    - vmware-eam
    - vmware-perfcharts
    - vmware-pod
    - vmware-postgres-archiver
    - vmware-rhttpproxy
    - vmware-sca
    - vmware-sps
    - vmware-statsmonitor
    - vmware-sts-idmd
    - vmware-stsd
    - vmware-updatemgr
    - vmware-vapi-endpoint
    - vmware-vmon
    - vmware-vpostgres
    - vmware-vpxd
    - vmware-vpxd-svcs
    - vmware-vsan-health
    - vmware-vsm
  7.0.0:
    - applmgmt
    - lookupsvc
    - lwsmd
    - observability
    - observability-vapi
    - pschealth
    - vlcm
    - vmafdd
    - vmcad
    - vmdird
    - vmonapi
    - vmware-analytics
    - vmware-certificateauthority
    - vmware-certificatemanagement
    - vmware-cis-license
    - vmware-content-library
    - vmware-eam
    - vmware-envoy
    - vmware-hvc
    - vmware-infraprofile
    - vmware-perfcharts
    - vmware-pod
    - vmware-rhttpproxy
    - vmware-sca
    - vmware-sps
    - vmware-statsmonitor
    - vmware-stsd
    - vmware-topologysvc
    - vmware-trustmanagement
    - vmware-updatemgr
    - vmware-vapi-endpoint
    - vmware-vdtc
    - vmware-vmon
    - vmware-vpostgres
    - vmware-vpxd
    - vmware-vpxd-svcs
    - vmware-vsan-health
    - vmware-vsm
    - vsphere-ui
    - vstats
    - vtsdb
    - wcp
  7.0.1:
    - applmgmt
    - lookupsvc
    - lwsmd
    - observability
    - observability-vapi
    - pschealth
    - vlcm
    - vmafdd
    - vmcad
    - vmdird
    - vmonapi
    - vmware-analytics
    - vmware-certificateauthority
    - vmware-certificatemanagement
    - vmware-cis-license
    - vmware-content-library
    - vmware-eam
    - vmware-envoy
    - vmware-hvc
    - vmware-infraprofile
    - vmware-perfcharts
    - vmware-pod
    - vmware-rhttpproxy
    - vmware-sca
    - vmware-sps
    - vmware-statsmonitor
    - vmware-stsd
    - vmware-topologysvc
    - vmware-trustmanagement
    - vmware-updatemgr
    - vmware-vapi-endpoint
    - vmware-vdtc
    - vmware-vmon
    - vmware-vpostgres
    - vmware-vpxd
    - vmware-vpxd-svcs
    - vmware-vsan-health
    - vmware-vsm
    - vsphere-ui
    - vstats
    - vtsdb
    - wcp
