---
- hosts: all
  tasks:
    - name: You are here
      debug:
        msg: '{{ ansible_test_splitter__test_changed }}'

    - name: Run ansible-test-splitter
      include_role:
        name: ansible-test-splitter
      vars:
        ansible_test_test_command: "{{ ansible_test_command }}"
        ansible_test_location: "{{ ansible_user_dir }}/{{ zuul.projects[ansible_collections_repo].src_dir }}"
        ansible_test_git_branch: "{{ zuul.projects['github.com/ansible/ansible'].checkout }}"
        ansible_test_ansible_path: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"
